### ISSUE TITLE
Value error while running source_localisation.py

### ISSUE THREAD

**Issue by anujanegi** [AliHashemi-ai/eeg#2]
@agramfort 

```
Running floyd-warshall
Traceback (most recent call last):
  File "/datasabzi/anuja/eeg/source_localisation.py", line 426, in <module>
    models_score[model_name]['emd'] = met.emd_score_subjects(
  File "/datasabzi/anuja/eeg/simulation/metrics.py", line 138, in emd_score_subjects
    score = emd_score_subj(y_true[sbj_idc], y_pred[sbj_idc],
  File "/datasabzi/anuja/eeg/simulation/metrics.py", line 150, in emd_score_subj
    score = emd_score(y_true, y_pred, labels_x)
  File "/datasabzi/anuja/eeg/simulation/emd.py", line 133, in emd_score
    ground_metric = _compute_full_ground_metric(subject, hemi=hemi,
  File "/home/anuja/anaconda3/envs/mne/lib/python3.9/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/anuja/anaconda3/envs/mne/lib/python3.9/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/anuja/anaconda3/envs/mne/lib/python3.9/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/datasabzi/anuja/eeg/simulation/emd.py", line 87, in _compute_full_ground_metric
    D = _mesh_all_distances(points, tris)
  File "/datasabzi/anuja/eeg/simulation/emd.py", line 22, in _mesh_all_distances
    A = mne.surface.mesh_dist(tris, points)
  File "/home/anuja/anaconda3/envs/mne/lib/python3.9/site-packages/mne/surface.py", line 1704, in mesh_dist
    edges = mesh_edges(tris).tocoo()
  File "/home/anuja/anaconda3/envs/mne/lib/python3.9/site-packages/mne/surface.py", line 1670, in mesh_edges
    raise ValueError(
ValueError: Cannot compute adjacency on a selection of triangles.
```

**Comment by anujanegi** [comment]
Also, @agramfort  
Encountered a warning in the lasso reweighted method. Do you think this is something we need to take care of somewhere?

running predictions on 10 lasso reweighted
`/datasabzi/anuja/eeg/simulation/sparse_regressor.py:85: ConvergenceWarning: Reweighted objective did not converge. You might want to increase the number of iterations of reweighting. Fitting data with very small alpha may cause precision problems.`
